# -*- coding: utf-8 -*-
"""Collision Handeling Hash Table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_4d3MZd-Nk3ImxbARKq_rNZBgCgMx5F
"""

class HashTable:
  def __init__(self):
    self.MAX = 10
    self.arr = [None for i in range (self.MAX)]
  def get_hash(self,key):
    hash = 0
    for char in key:
        hash=hash+ord(char)
    return hash % self.MAX
  def __getitem__(self,key):
    h = self.get_Hash(index)
    return self.arr[h]
  def __setitem__(self,key,val):
    h= self.get_hash(key)
    self.arr[h] = val

t = HashTable()
t.get_hash("march 6")
t.get_hash("march 8")

t.get_hash("march 17")

"""Hash Table Collision Handleing Using Chaining"""

class HashTable:
    def __init__(self):
        self.MAX = 10
        self.arr = [[] for i in range(self.MAX)]

    def get_hash(self, key):
        hash = 0
        for char in key:
            hash += ord(char)
        return hash % self.MAX

    def __getitem__(self, key):
        arr_index = self.get_hash(Key)
        for kv in self.arr[arr_index]:
            if kv[0] == key:
                return kv[1]